### ISSUE TITLE
Consistency on nash.ExecFile

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/nash#157] opened 2017-01-12 19:22 UTC
I think I found a problem with the current ExecFile implementation. I was running some Go code using ExecFile, like this:

```
shell.ExecFile("script", "arg1", "arg2")
```

Inside the shell script the variables will be:

```
ARGS[0] = "arg1"
ARGS[1] = "arg2"
```

When I tried to seamlessly run the same script on my shell, it broke. I found out that when executing from the shell the args will be:

```
ARGS[0] = "script"
ARGS[1] = "arg1"
ARGS[2] = "arg2"
```

Which makes sense, but the ExecFile implementation does not maintain this patterns, and this lack of uniformity kills my ability to interchangeably execute a script from Go or from the shell.

Would a fix on the ExecFile be a good idea ? What you think @tiago4orion ?

**Comment by tiago4orion** [comment] 2017-01-19 12:37
Sorry for the late reply. 

ARGS[0] should be passed setting the script name (process name). But maybe changing the function name improves the meaning. Anyway, `ExecFile` must work like syscall `execve(2)`.

**Comment by katcipis** [comment] 2017-01-19 15:51
@tiago4orion why it has to behave like the syscall ? It is not a syscall...it is a high level function on a high level language, I'm a little confused on this one. Is there some use case where behaving like this is desirable to the user ?

**Comment by tiago4orion** [comment] 2017-01-19 16:11
`argv[0]` containing the program name is a convention used in operating systems (at least unix'es) and programming languages (C, Go, Java, etc). 

There's several use cases for software behaving differently depending on argv[0] value. A good example is busybox, where there's only one big static binary called busybox, and lots of hardlinks of core command utilities pointing to it. When someone try to execute the `ls` hardlink, shell sets argv[0] of busybox program as `ls` and then it behaves like `ls`.

**Comment by tiago4orion** [comment] 2017-01-26 19:07
Closing as 'works as expected' for now. It's not a bug, maybe we can discuss improving the API in the future.
Thanks!

**Closed by tiago4orion** 2017-01-26 19:07 UTC
